# Generated by Django 4.2.3 on 2023-07-14 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_author_category_comment_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.category'),
            preserve_default=False,
        ),
    ]
